### ISSUE TITLE
.bashrcがrmされる

### ISSUE THREAD

**Issue by MiraiHattori** [kyawawa/dot-files#1]
https://github.com/kyawawa/dot-files/blob/master/make-link.sh#L7 について，先ほど.bashrcをremoveしてしまう事故を起こしてしまったので，mv $HOME/.bashrc $HOME/.bashrc.bak.yyyymmddみたいにするとよいと思います．

**Comment by kyawawa** [comment]
そうですね．実態があるときはバックアップを取るようにしようかと思います．

**Comment by kyawawa** [comment]
整理を兼ねてしまったので見づらいですが， 4afd00f で対応しました．
フィードバックありがとうございました．
